version: '3'
services:
#Service odoo toma el Dockerfile de ./odoo
 odoo:
  build: ./odoo
  ports:
  - "8069:8069"
  - "5432:5432"
  #Cambiarlo para el home de cada usuario
  volumes:
  - /home/javierfp/odoo:/opt/odoo/src
  - /home/javierfp/odoo/conf:/opt/odoo/conf
  - /home/javierfp/odoo/log:/var/log/odoo
